apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah staging"

images:
  - name: panama69/randomquotes-k8s
    newName: panama69/randomquotes-k8s
    newTag: "lastest"

patches:
  - target:
      kind: Ingress
      name: randomquotes-ingress-nginx
    path: randomquotes-ingress-nginx.yaml
